# Generated by Django 3.2.7 on 2021-09-04 10:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('iso_code', models.CharField(db_index=True, max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(db_index=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
