# Generated by Django 3.2.7 on 2021-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_alter_country_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='fips',
            field=models.CharField(max_length=2, null=True, verbose_name='FIPS Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(default='', max_length=2, verbose_name='2 Digit ISO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default=0, max_length=3, verbose_name='3 Digit ISO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(default=0, verbose_name='Region Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.IntegerField(default=0, verbose_name='Sub-Region Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='un',
            field=models.IntegerField(default=0, verbose_name='United Nations Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
